"""postgis

Revision ID: 1f81f72ce66d
Revises: 
Create Date: 2024-10-09 16:52:23.628951

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f81f72ce66d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DROP EXTENSION IF EXISTS postgis_tiger_geocoder")
    op.execute("DROP EXTENSION IF EXISTS postis_topology")
    op.execute("DROP EXTENSION IF EXISTS fuzzystrmatch")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass